### ISSUE TITLE
`marginaleffects` functions fail with non-linear `brms` fit.

### ISSUE THREAD

**Issue by Tristan-Siegfried** [vincentarelbundock/marginaleffects#759]
`brms` fit with only one variable, when it enter non-linearly, leads to errors when used with e.g. `slopes` in `marginaleffects`.

### Reproducible example
```
library(brms)
library(marginaleffects)
fit1 <- brm(bf(hp~exp(test), test~(1|am)+mpg, nl=T), data=mtcars, backend="cmdstanr")
slopes(fit1)
```
Gives 
```
Error: These variable names are forbidden to avoid conflicts with the outputs of
  `marginaleffects`:
  "rowid"
  Please rename your variables before fitting the model.
```

### Commentary
Notably, `predictions(fit1)` still works, so it is something particular to `slopes`, `comparisons`, etc.

That being said, 
```
fit2<-brm(bf(hp~exp(test)+cyl, test~(1|am)+mpg, nl=T), data=mtcars, backend="cmdstanr")
slopes(fit2)
```
Does work properly! So it is something about just having one variable that is doing something problematic.

Lastly, I just want to flag that all of the above remains true if you replace `exp` with `log`, so the type of non-linear function does not appear to be the issue.

**Comment by vincentarelbundock** [comment]
Thanks for the report and very useful reproducible example.

Version 0.11.1.9010 from Github no longer generates this error.

However, the results look really non-sensical. Do you think that this is because we are looking at a toy model, or do you think there is something more fundamentally wrong? Would you be able to try it on a more realistic model?

I don't have experience with the `nl` argument in `brms`...

**Comment by vincentarelbundock** [comment]
Thanks a lot for this.

I think it might be worth it to look at a less pathological case, because it’s not clear to me exactly what the problem is here. Take this very simple example:

``` r
library(brms)
library(marginaleffects)

fit = brm(
    bf(Sepal.Length ~ exp(test), test ~ (1 | Species) + Petal.Width, nl = TRUE),
    data = iris, backend = "cmdstanr")

avg_comparisons(fit, variables = "Petal.Width")
# 
#         Term Contrast Estimate 2.5 % 97.5 %
#  Petal.Width       +1     0.88 0.616   1.08
# 
# Columns: term, contrast, estimate, conf.low, conf.high
```

We can replicate the results of `comparisons()` “manually” pretty closely with:

``` r
dat_lo = transform(iris, Petal.Width = Petal.Width - 0.5)
dat_hi = transform(iris, Petal.Width = Petal.Width + 0.5)
pred_lo = posterior_epred(fit, newdata = dat_lo, summary = FALSE)
pred_hi = posterior_epred(fit, newdata = dat_hi, summary = FALSE)
mean(apply(pred_hi - pred_lo, 1, median))
# [1] 0.8830756
```

We can also replicate the `slopes()` output:

``` r
avg_slopes(fit, variables = "Petal.Width")
# 
#         Term Estimate 2.5 % 97.5 %
#  Petal.Width    0.879 0.616   1.08
# 
# Columns: term, estimate, conf.low, conf.high

dat_lo = transform(iris, Petal.Width = Petal.Width - 1e-4 / 2)
dat_hi = transform(iris, Petal.Width = Petal.Width + 1e-4 / 2)
pred_lo = posterior_epred(fit, newdata = dat_lo, summary = FALSE)
pred_hi = posterior_epred(fit, newdata = dat_hi, summary = FALSE)
mean(apply((pred_hi - pred_lo) / 1e-4, 1, median))
# [1] 0.8822177
```

So when I try the functions on a more reasonable example, things seem to work fine. I’m not sure what’s going on with the pathological example, but before investigating further I’d like to know if you can replicate the problem with a less weird case.

**Comment by vincentarelbundock** [comment]
Great news! I'll close this issue, but feel free to open a new one if you do end up finding a problem.

**Comment by WillemSleegers** [comment]
I have a relatively simple example involving the `categorical()` family in brms. It gives me the same error ("Error: These variable names are forbidden to avoid conflicts with the outputs of `marginaleffects`: "rowid"") when using `avg_comparisons()`.

```
library(tidyverse)
library(brms)
library(marginaleffects)

probs <- c(0.2, 0.3, 0.5)
n <- 100

data <- tibble(
  response = sample(letters[seq_along(probs)],
    size = n, prob = probs, replace = TRUE
  )
)

fit <- brm(response ~ 1, data = data, family = categorical())

avg_comparisons(fit)
```

**Comment by vincentarelbundock** [comment]
Thanks for the report @WillemSleegers. I just pushed a new version to Github with a more informative error message:

``` r
library(brms)
library(marginaleffects)

probs <- c(0.2, 0.3, 0.5)
n <- 100

data <- data.frame(
  response = sample(letters[seq_along(probs)], size = n, prob = probs, replace = TRUE),
  x = rnorm(n)
)

fit <- brm(response ~ 1, data = data, iter = 100, family = categorical(), backend = "cmdstanr")

# This function makes no sense without predictors
avg_comparisons(fit)
# Error: There is no valid predictor variable. Please change the `variables`
#   argument or supply a new data frame to the `newdata` argument.

# This function still makes sense without predictors
predictions(fit)
# 
#  Group Estimate  2.5 % 97.5 %
#      a    0.172 0.0898  0.246
#      a    0.172 0.0898  0.246
#      a    0.172 0.0898  0.246
#      a    0.172 0.0898  0.246
#      a    0.172 0.0898  0.246
# --- 290 rows omitted. See ?avg_predictions and ?print.marginaleffects --- 
#      c    0.518 0.4254  0.609
#      c    0.518 0.4254  0.609
#      c    0.518 0.4254  0.609
#      c    0.518 0.4254  0.609
#      c    0.518 0.4254  0.609
# Columns: rowid, group, estimate, conf.low, conf.high, response
```

**Comment by WillemSleegers** [comment]
@vincentarelbundock Thanks! That helps because I was afraid something was wrong with the code (it being unsupported, for example), rather than that the function makes no sense without predictors.

I do have a question though. How can I compare the proportions between the different levels in the outcome (`response`)? My goal was to run `avg_comparisons()` and somehow specify that it is an intercept-only model so it would compare the levels in the outcome.

**Comment by vincentarelbundock** [comment]
Great. You can use the hypothesis argument (see the vignette).

**Comment by WillemSleegers** [comment]
I'm sorry but it's still not clear to me how to specify that it's an intercept-only model. If I set the `hypothesis` argument to for example `sequential`, which makes intuitive sense to me, it still complains. 

The documentation clearly shows how it works once you have a predictor you can specify in `variables`, but it's not clear to me how I can use it when there isn't a predictor (only the intercept). 

Sorry if I'm being dense and I also realize this might not be the best place to discuss this!
